name: QMAid end-to-end test

on:
  push:
  workflow_dispatch:

jobs:
  run-end-to-end-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build test app with Maven
      run: mvn --batch-mode --update-snapshots verify --file tools/test-microservice/pom.xml
      
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('tools/test-microservice/pom.xml') }}
        restore-keys: ${{ runner.os }}-test-app-maven-repo
      
    - name: Build QMAid CLI with Maven
      run: mvn package appassembler:assemble
    - run: mkdir test-deploy && cp -r target/appassembler/* test-deploy
    - uses: actions/upload-artifact@v3
      with:
        name: qmaid
        path: test-deploy
        
    - name: Execute QMAid
      run: sudo ./test-deploy/bin/qmaid -p tools/test-microservice -a tools/test-microservice/src/main/java/com/example/restservice/RestServiceApplication.java -m ~/.m2/repository -wd
      
    - run: mkdir test-result && cp results/* test-result
    - uses: actions/upload-artifact@v3
      with:
        name: result
        path: test-result
