name: QMAid end-to-end test

on:
  push:
  workflow_dispatch:

jobs:
  run-end-to-end-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build test app with Maven
      run: mvn --batch-mode --update-snapshots verify --file tools/test-microservice/pom.xml
      
    # - run: mkdir test-deploy-repo && cp -r .m2/repository/* test-deploy-repo
    - uses: actions/upload-artifact@v3
      with:
        name: test-deploy-repo
        path: .m2/repository
      
    - name: Build QMAid CLI with Maven
      run: mvn package appassembler:assemble
    # - run: mkdir test-deploy-app && cp -r target/appassembler/* test-deploy-app
    - uses: actions/upload-artifact@v3
      with:
        name: test-deploy-app
        path: target/appassembler
        
    - name: Execute QMAid
      run: sudo ./test-deploy-app/bin/qmaid -p tools/test-microservice -a tools/test-microservice/src/main/java/com/example/restservice/RestServiceApplication.java -m test-deploy-repo -wd
      
    # - run: mkdir test-deploy-result && cp results/* test-deploy-result
    - uses: actions/upload-artifact@v3
      with:
        name: test-deploy-result
        path: results
