name: QMAid end-to-end test

on:
  push:
  workflow_dispatch:

jobs:
  build-test-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build test app with Maven
      run: mvn --batch-mode --update-snapshots verify --file tools/test-microservice/pom.xml
      
    - name: Build QMAid CLI with Maven
      run: mvn package appassembler:assemble
    - run: mkdir test-deploy && cp -r target/appassembler/* test-deploy
    - uses: actions/upload-artifact@v3
      with:
        name: qmaid
        path: test-deploy
        
    - name: Execute QMAid
      run: ./test-deploy/bin/qmaid -p tools/test-microservice -a tools/test-microservice/src/main/java/com/example/restservice/RestServiceApplication.java -m $HOME/.m2/repository -wd
      
    - run: mkdir test-result && cp results/* test-result
    - uses: actions/upload-artifact@v3
      with:
        name: result
        path: test-result
