name: QMAid end-to-end test

on:
  push:
  workflow_dispatch:

jobs:
  run-end-to-end-test:
    runs-on: ubuntu-latest
    env:
      M2_REPO: ${{ github.workspace }}/test-deploy-repo
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build test app with Maven
      run: mvn --batch-mode --update-snapshots verify --file tools/test-microservice/pom.xml

    - name: Save test app dependencies
      run: sudo mkdir -p /root/.m2/repository && sudo cp -r ~/.m2/repository/* /root/.m2/repository      
  
    - name: Build QMAid CLI
      run: mvn package appassembler:assemble
    
    - run: chmod +x ${{ github.workspace }}/tools/mta-cli-5.2.1/bin/mta-cli
    
    - name: Execute QMAid
      run: sudo ./target/appassembler/bin/qmaid -p tools/test-microservice -a tools/test-microservice/src/main/java/com/example/restservice/RestServiceApplication.java -m /root/.m2/repository
      
    - uses: actions/upload-artifact@v3
      with:
        name: test-deploy-result
        path: results
